
Skip to Main Content
[Alt+S]

    Amazon Athena

    Query editor

    Amazon Athena

    Query editor

Workgroup

    Editor
    Recent queries
    Saved queries
    Settings

Data
Data source
Catalog
Database
Tables and views
Tables (2)

raw_comments
Partitioned
raw_trending
Partitioned

Views (0)

 
SQL
Ln 47, Col 1
Reuse query results
up to 60 minutes ago

Completed
Time in queue:
86 ms
Run time:
758 ms
Data scanned:
202.74 KB
Results (20)

#
	
region
	
date
	
video_id
	
title
	
channel
	
video_published_at
	
views
	
video_likes
	
comment_count
	
avg_comment_likes
#
	
region
	
date
	
video_id
	
title
	
channel
	
video_published_at
	
views
	
video_likes
	
comment_count
	
avg_comment_likes
1
	
US
	
2025-11-19
	
Mwh7WFCW3f8
	
Chapter 6 Finale Live Event | Teaser Trailer
	
Fortnite
	
2025-11-19T19:00:23Z
	
122368
	
18025
	
1
	
0.0
2
	
US
	
2025-11-19
	
gBuecIOZLV4
	
Left For Good
	
Bad Omens - Topic
	
2025-11-18T17:01:17Z
	
212635
	
12697
	
0
	
0.0
3
	
US
	
2025-11-19
	
HRdAWMvc0GU
	
Mega Zeraora Reveal for Pokemon Legends Z-A Mega Dimension
	
Austin John Plays
	
2025-11-19T14:24:35Z
	
53342
	
3333
	
0
	
0.0
4
	
US
	
2025-11-19
	
3MfD_V0o_4U
	
New LOS TACO BLOCKS + Taco Tuesday Admin Abuse
	
CaylusBlox
	
2025-11-19T00:10:38Z
	
1977632
	
30247
	
0
	
0.0
5
	
US
	
2025-11-19
	
VwPJ2-LzS6A
	
Hear My Hope
	
Hazbin Hotel - Topic
	
2025-11-19T08:03:48Z
	
145726
	
9239
	
0
	
0.0
6
	
US
	
2025-11-19
	
QKYFfYLe5rs
	
Moana | Official Teaser
	
Disney
	
2025-11-17T17:00:47Z
	
4805935
	
37051
	
0
	
0.0
7
	
US
	
2025-11-19
	
p2POGKxC0G8
	
I Worked Nights At A Bici Shop
	
CaseOh
	
2025-11-18T23:01:12Z
	
329871
	
10032
	
0
	
0.0
8
	
US
	
2025-11-19
	
jMrNjN0-osw
	
BAD OMENS - Left For Good (Official Music Video)
	
SUMERIAN
	
2025-11-18T17:00:20Z
	
499411
	
54585
	
0
	
0.0
9
	
US
	
2025-11-19
	
BKOVzHcjEIo
	
Dhurandhar Official Trailer | Ranveer Singh | Aditya Dhar | In Cinemas 5th December 2025
	
JioStudios
	
2025-11-18T06:50:49Z
	
17121903
	
334946
	
0
	
0.0
10
	
US
	
2025-11-19
	
cfPHxW47E60
	
I Became The OWNER of Roblox Biggest Games
	
LazarLazar
	
2025-11-18T22:26:12Z
	
1415192
	
43208
	
0
	
0.0
11
	
US
	
2025-11-19
	
vr_ECKYkYUQ
	
Christmas Song Playlist 🎄 Top 50 Christmas Songs of All Time 🎅 Best Merry Christmas Music
	
Christmas Songs and Carols - Love to Sing
	
2025-11-19T12:15:10Z
	
39869
	
302
	
0
	
0.0
12
	
US
	
2025-11-19
	
wZetaKE7KQo
	
Warhammer 40,000: Darktide - Hive Scum Class Reveal | Cinematic Trailer
	
Fatshark
	
2025-11-18T17:01:14Z
	
188934
	
9677
	
0
	
0.0
13
	
US
	
2025-11-19
	
3w8W5NiSRFU
	
Path of Exile Creator Explains How Modern Games Play You
	
Asmongold TV  
	
2025-11-19T03:00:09Z
	
427354
	
16786
	
0
	
0.0
14
	
US
	
2025-11-19
	
LuJpdvb5bDk
	
PIRLO - EL FICTICIO 🐛 [RIP Blessd] (Audio Oficial)
	
Pirlo 420
	
2025-11-19T11:52:15Z
	
490352
	
96846
	
0
	
0.0
15
	
US
	
2025-11-19
	
5VYsnngkS_U
	
Project Hail Mary | Official Trailer 2
	
Amazon MGM Studios
	
2025-11-18T14:00:01Z
	
5218839
	
49890
	
0
	
0.0
16
	
US
	
2025-11-19
	
gzCZpHELFoY
	
The WORST Clash Royale Clips
	
Jynxzi
	
2025-11-18T23:15:56Z
	
506885
	
12106
	
0
	
0.0
17
	
US
	
2025-11-19
	
yd_uG3TtREs
	
BABYMONSTER - ‘PSYCHO’ M/V
	
BABYMONSTER
	
2025-11-18T15:00:01Z
	
11393550
	
598738
	
0
	
0.0
18
	
US
	
2025-11-19
	
Q3sdiIq0bGg
	
Honest Trailers | Wicked
	
Screen Junkies
	
2025-11-18T18:00:34Z
	
253851
	
13034
	
0
	
0.0
19
	
US
	
2025-11-19
	
ppp7dMhzrz8
	
Lil Baby - Real Shit
	
LilBabyVEVO
	
2025-11-19T17:01:34Z
	
110197
	
14788
	
0
	
0.0
20
	
US
	
2025-11-19
	
sNHHfHIewpU
	
Pokémon Legends: Z-A – Mega Dimension | Get Charged Up with Mega Zeraora!
	
The Official Pokémon YouTube channel
	
2025-11-19T14:01:18Z
	
504515
	
29984
	
0
	
0.0
© 2025, Amazon Web Services, Inc. or its affiliates.

    Privacy
    Terms

